stack_name: legion-td-discord-bot-prod
project_code: legion-td-discord-bot-prod
parameters:
  EnableDebug: "false"
  DiscordApplicationId: "1015271519414399038"
  DiscordPublicKey: 42be1d3d4136ed14b3a46a60bb11fe92c73c0d84be9337f3e6f11e21edf6e75d
  GoogleApiKey: {{ environment_variable.GOOGLE_API_KEY }}
  GoogleSheetId: {{ environment_variable.GOOGLE_SHEET_ID_PROD }}
  ChallongeApiKey: {{ environment_variable.CHALLONGE_API_KEY }}
  AlertWebhook: {{ environment_variable.ALERT_WEBHOOK }}
