stack_name: legion-td-discord-bot-dev
project_code: legion-td-discord-bot-dev
parameters:
  EnableDebug: "true"
  DiscordApplicationId: "1058247991867219990"
  DiscordPublicKey: f5f2ad3d28b06fb464d8e9ee6d3667e149392467341759d4811ee6996d2e918a
  GoogleApiKey: {{ environment_variable.GOOGLE_API_KEY }}
  GoogleSheetId: {{ environment_variable.GOOGLE_SHEET_ID_DEV }}
  ChallongeApiKey: {{ environment_variable.CHALLONGE_API_KEY }}
  AlertWebhook: {{ environment_variable.ALERT_WEBHOOK }}
